### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by Cervator** [Terasology/LandOfTerra#1]
@esapetri - mind tidying up some of the license headers and author tags? Looks like some copy paste has gotten in, from classes authored by immortius or begla for instance.

BitScrampler.java looks like a copy of the top from FastRandom in the engine (references an author that inspired FastRandom), yet has different code, including some commented out stuff (probably should be deleted). Able to correct the sourcing in there? Maybe add some links to where stuff came from including what if any licensing.

It also doesn't need the API tag if it is in a module, although if it is useful in general it might be an idea to move it to the engine - at which point it would indeed need the API tag :-)

**Comment by esapetri** [comment]
Ill try tidying it up. It is mostly mess right now because it evolves so fast.

**Comment by jdrueckert** [comment]
There'd be more than a bit of general license header and author tag clean up necessary to get this revived again.
I'll close this issue and we can revisit foraging the gist of this module when foraging TTA/WoodAndStone and related modules.
